INSERT INTO SHOPPING_LIST(ID, TITLE)
VALUES (1, 'test lijst');

INSERT INTO ITEM(ID, IMAGE, INGREDIENTS, NAME, QUANTITY, AMOUNT, TYPE)
VALUES (1, '', 'zout,peper', 'Pizza hawai', 1, 320, 0);

INSERT INTO APPLICATION_USER(ID, USERNAME, PROVIDER)
VALUES (1, 'test', 'github')
